name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_app.py --maxfail=5 --disable-warnings

    - name: Run SSH_HOST
      env:
        SSH_HOST: ${{ vars.SSH_HOST }}
      run: echo $SSH_HOST

    - name: Run SSH_KEY
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: echo $SSH_KEY
    
    - name: Run JOB_NAME
      run: echo ${{ vars.JOB_NAME }}

    - name: Run connect
      run: ls -al /path/to/private/

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Run SSH_HOST1
      env:
        SSH_HOST1: ${{ vars.SSH_HOST }}
      run: echo $SSH_HOST1
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 194.59.40.195
        username: vitaly
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbG0ps0HoXVUHTyYx/fu3WOfJ9ljs4oe8eNSs/gfkQupU5D5nj8Qtbntk0AAljIR3FA85LijJjfNw5Q+s7O7bnSQjNAdO9zrqdq8C1DIy6XeTJr8ykTmhDeX3M68w6mrsI2ch52oLNPLHY4ZCxJ/Wbz3zhFGd9FaffiUKPxbY34x8Ll5kvIg0vjBwW2LI464ABWMimoEWnqQcm3tmytPi3GUmLlnuItXx2ZbKhMUmdOCXnokFJWX7Y87GqJ9D0+2IXBqafupNmVH+zWY4ox5PrmI8xEpoB8elz9XkrEATmpTumvdLLK0ECL+S0IHhPHACvPG8BMZ61hoy1VgKhLLLbLg42vumqJCZDbLlJHVKDcw3PN3NDhUFL7hIJVE4v83LXIzY7RbAtZ163k/G1sCqt8G5SzxipLmIIM4ed6WtBGlDoUzVMc90NFEOzs517iAdHT0sHon6F26REe+UvlOsIfTehulVmgDl4hWq1q4fCMi82yC6gpvfG5afhHD0tn4Hfo43Rthf3Ac51nzgO193Y7K+cTaGw4o9Ju6cCqPZAoVYDUqTIKPpKeOWAGNbNz86XksIhZ06Nk1BJFi92UBrBQN9fw+CW421yEk/tW8wtUIU58MM6fSBZY/47TWXS/swRlHUFRlKdu2Er8SktiKC1Nlz1FkFiEuxm3jADO5blCw== vitaly@TANYA
        script: |
          cd /home/vitaly/deploy
          sudo git pull origin main
          sudo pip install -r requirements.txt
          python app.py
