name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_app.py --maxfail=5 --disable-warnings
    
    - name: Run connect
      run: pwd

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Run SSH_HOST1
      env:
        SSH_HOST1: ${{ vars.SSH_HOST }}
      run: echo $SSH_HOST1
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_SSH_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          echo "Connected to ${{ secrets.REMOTE_HOST }}"
          echo "User: ${{ secrets.REMOTE_SSH_USER }}"
          echo "Key: ${{ secrets.REMOTE_SSH_KEY }}"
          cd /home/vitaly/deploy
          git clone https://github.com/belkin-vitaliy/pipeline-lab5.git
          cd pipeline-lab5
          python3 app.py &
