name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_app.py --maxfail=5 --disable-warnings

    - name: Run SSH_HOST
      env:
        SSH_HOST: ${{ vars.SSH_HOST }}
      run: echo $SSH_HOST

    - name: Run SSH_KEY
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: echo $SSH_KEY
    
    - name: Run JOB_NAME
      run: echo {{ vars.JOB_NAME }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Run SSH_HOST1
      env:
        SSH_HOST1: ${{ vars.SSH_HOST }}
      run: echo $SSH_HOST1
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 194.59.40.195
        username: vitaly
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/vitaly/deploy
          sudo git pull origin main
          sudo pip install -r requirements.txt
          python app.py
